### ISSUE TITLE
Profile edit is broken because of phone number format restrictions

### ISSUE THREAD

**Issue by evan10s** [HackGT/bolt#142]
The phone number input field on the Profile page wants a number like 1234567890 but we have a magic text input that makes the phone number input like (123) 456-7890 (client-side), so you can't submit profile information changes.

**Comment by ayush-goyal** [comment]
I'm not sure I see this bug? I can change my phone number fine

**Comment by evan10s** [comment]
Yeah, I see that too on Chrome on Android.  Was it working for you on desktop?  That's where I had the issue

**Comment by ayush-goyal** [comment]
It's working for me on desktop too on Chrome

**Comment by evan10s** [comment]
Closing, can't reproduce
